# Generated by Django 5.2.9 on 2025-12-19 17:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_phase', models.CharField(choices=[('IDLE', 'Idle'), ('ANALYZING', 'Analyzing Gaps'), ('TEACHING_PREREQ', 'Teaching Prerequisites'), ('TEACHING_MAIN', 'Teaching Main Topic'), ('PRACTICING_CODE', 'Practicing Code'), ('PRACTICING_DEBUG', 'Practicing Debugging'), ('COMPLETED', 'Completed')], default='IDLE', max_length=50)),
                ('current_topic', models.CharField(blank=True, max_length=200, null=True)),
                ('failed_prereqs', models.JSONField(blank=True, default=list)),
                ('context', models.JSONField(blank=True, default=dict)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
