import React from 'react';

const CodeDisplay = ({ code }) => {
  if (!code) return null;

  const cleanCode = code.trim();

  return (
    <div className="mt-6">
      <h3 className="text-2xl font-semibold text-indigo-700 mb-3 border-b pb-2">
        Generated JSX Source Code
      </h3>
      <p className="text-sm text-gray-600 mb-2">
        Review the React component code generated by the backend below.
      </p>
      <div className="bg-gray-800 p-4 rounded-lg overflow-x-auto shadow-2xl font-mono text-sm text-green-300">
        <pre>
          <code>{cleanCode}</code>
        </pre>
      </div>
    </div>
  );
};

export default CodeDisplay;
