# Generated by Django 5.1.1 on 2025-12-13 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TutorSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_email', models.EmailField(max_length=254, unique=True)),
                ('current_topic', models.CharField(blank=True, max_length=255, null=True)),
                ('subtopics', models.JSONField(blank=True, default=list)),
                ('current_index', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('IDLE', 'Idle'), ('TEACHING', 'Teaching'), ('AWAITING_ANSWER', 'Awaiting Answer'), ('AWAITING_SWITCH_CONFIRMATION', 'Awaiting Switch Confirmation')], default='IDLE', max_length=50)),
                ('switch_topic_buffer', models.CharField(blank=True, max_length=255, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
