# Generated by Django 5.1.1 on 2025-12-13 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorsession',
            name='user_email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
    ]
